apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-app
  annotations:
    nginx.ingress.kubernetes.io/user-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/config
            pathType: Prefix
            backend:
              service:
                name: "frontend-svc"
                port:
                  number: 80
          - path: /api/productos
            pathType: Prefix
            backend:
              service:
                name: "backend1-svc"
                port:
                  number: 80      
          - path: /api/init-products
            pathType: Prefix
            backend:
              service:
                name: "backend1-svc"
                port:
                  number: 80   
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "frontend-svc"
                port:
                  number: 80                                               